name: mask-wearing-classification-with-cicd

on:
  push:
    branches:
      - experiment
  pull_request:
    branches:
      - experiment

jobs:
  integration:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest httpx
          pip install -r api/requirements.txt

      - name: Run tests
        env:
            CI: "true"   # <-- tells main.py we're in CI
        run: pytest -v


  deploy:
    name: Build and Deploy Docker
    runs-on: ubuntu-latest
    needs: integration   # <-- ensures tests pass before deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t mask-wearing-classification-with-cicd:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag mask-wearing-classification-with-cicd:latest ${{ secrets.DOCKER_USERNAME }}/mask-wearing-classification-with-cicd:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mask-wearing-classification-with-cicd:latest
